productsSample = [
    # browsing / catalog
    "cửa hàng đang bán những điện thoại nào",
    "liệt kê các mẫu điện thoại hiện có",
    "shop hiện có những dòng điện thoại nào",
    "cho tôi xem danh sách điện thoại",
    "có những sản phẩm nào trong cửa hàng",
    "cơ sở dữ liệu có những điện thoại nào",

    # buying intent
    "tôi muốn mua điện thoại",
    "điện thoại nào giá rẻ",
    "gợi ý điện thoại dưới 5 triệu",

    # info intent
    "điện thoại này có pin bao nhiêu",
    "giá của sản phẩm này là bao nhiêu",
    "Điện thoại realme c51 giá bao nhiêu?",
    "realme c51 3gb/64gb hiện còn hàng không?",
    "realme c51 6gb/256gb có mấy màu?",
    "pin realme c51 dùng được bao lâu?",
    "realme c51 có hỗ trợ sạc nhanh không?",
    "samsung galaxy a05s giá hiện tại là bao nhiêu?",
    "galaxy a05s có phù hợp cho học sinh không?",
    "samsung a05s chơi game nhẹ có ổn không?",
    "galaxy a05s có khuyến mãi gì không?",
    "samsung a05s có mấy phiên bản ram?",
    "xiaomi redmi 12 4gb/128gb giá bao nhiêu?",
    "redmi 12 8gb/128gb khác gì bản 4gb?",
    "redmi 12 pin bao nhiêu mAh?",
    "redmi 12 có chống nước không?",
    "redmi 12 màn hình bao nhiêu inch?",
    "điện thoại poco c65 giá hiện tại là bao nhiêu?",
    "poco c65 8gb/256gb có phù hợp chơi game không?",
    "poco c65 có mấy màu?",
    "poco c65 pin trâu không?",
    "poco c65 có hỗ trợ sạc nhanh không?",
    "infinix note 40 pro giá bao nhiêu?",
    "note 40 pro có sạc nhanh mấy w?",
    "note 40 pro có màn hình amoled không?",
    "infinix note 40 pro chơi game có nóng không?",
    "note 40 pro camera chụp ảnh có đẹp không?",
    "vivo y03 giá bao nhiêu?",
    "vivo y03 có mấy màu?",
    "vivo y03 pin bao nhiêu mAh?",
    "vivo y03 phù hợp cho người lớn tuổi không?",
    "vivo y03 có hỗ trợ 4g không?",
    "nokia 220 4g giá bao nhiêu?",
    "nokia 220 4g pin dùng được mấy ngày?",
    "nokia 220 4g có bluetooth không?",
    "nokia 220 4g phù hợp cho ai?",
    "nokia 3210 4g có những màu nào?",
    "nokia 3210 4g giá hiện tại bao nhiêu?",
    "nokia 3210 4g pin có bền không?",
    "nokia 3210 4g có nghe gọi rõ không?",
    "điện thoại nothing phone 2 giá bao nhiêu?",
    "nothing phone 2 có đèn glyph không?",
    "nothing phone 2 dùng chip gì?",
    "nothing phone 2 có chống nước không?",
    "xiaomi 13t pro giá bao nhiêu?",
    "xiaomi 13t pro camera có tốt không?",
    "xiaomi 13t pro chơi game nặng có ổn không?",
    "xiaomi 13t pro có sạc nhanh không?",
    "so sánh realme c51 và redmi 12",
    "điện thoại nào dưới 3 triệu đáng mua?",
    "điện thoại pin trâu giá rẻ nên chọn mẫu nào?",
    "điện thoại cho học sinh dưới 4 triệu?",
    "điện thoại ram 8gb giá rẻ có những mẫu nào?",
    "máy nào chụp ảnh đẹp trong tầm giá 5 triệu?",
    "điện thoại nào phù hợp cho người lớn tuổi?",
    "điện thoại màn hình lớn pin khỏe?",
    "điện thoại giá rẻ nhưng dùng ổn định?",
    "mẫu điện thoại nào đang khuyến mãi?",
    "điện thoại nào có sạc nhanh giá rẻ?",
    "máy nào chơi game liên quân mượt?",
    "điện thoại nào pin trên 5000mah?",
    "điện thoại giá rẻ có 4g không?",
    "mẫu nào phù hợp làm máy phụ?",
    "điện thoại dưới 2 triệu có không?",
    "điện thoại dưới 3 triệu có những mẫu nào?",
    "điện thoại android giá rẻ nên mua?",
    "điện thoại nào đáng mua nhất hiện tại?",
    "máy nào phù hợp cho sinh viên?",
    "điện thoại nào bán chạy ở cửa hàng?",
    "điện thoại nào có bảo hành chính hãng?",
    "điện thoại nào pin bền nhất?",
    "điện thoại giá rẻ cho người già?",
    "điện thoại nghe gọi tốt pin trâu?",
    "điện thoại nào phù hợp làm quà tặng?",
    "điện thoại nào có camera ổn trong tầm giá?",
    "điện thoại nào dùng bền ít lỗi?",
    "điện thoại nào giá rẻ nhưng cấu hình ổn?",
    "điện thoại nào phù hợp cho học online?",
    "điện thoại nào pin khỏe cho đi công tác?",
    "điện thoại nào có ram lớn giá thấp?",
    "điện thoại nào đang có ưu đãi tốt?",
    "điện thoại nào nên mua trong tầm 3 triệu?",
    "điện thoại nào đáng mua nhất cho người mới dùng smartphone?",
    "điện thoại nào hỗ trợ sạc nhanh rẻ nhất?",
    "điện thoại nào phù hợp cho tài xế?"
]

chitchatSample = [
    "Thời tiết hôm nay đẹp nhỉ?",
    "Hôm nay trời có nóng không?",
    "Bạn khỏe không?",
    "Hôm nay bạn làm việc có vui không?",
    "Cửa hàng hôm nay đông khách không?",
    "Bạn tên là gì?",
    "Bạn làm việc ở đây lâu chưa?",
    "Ngoài bán điện thoại thì cửa hàng còn làm gì nữa?",
    "Giờ này cửa hàng còn mở không?",
    "Cuối tuần cửa hàng có nghỉ không?",
    "Bạn thích Android hay iPhone hơn?",
    "Bạn hay dùng điện thoại hãng nào?",
    "Hôm nay là thứ mấy?",
    "Cuối tuần này có kế hoạch gì không?",
    "Bạn có mệt không?",
    "Nói chuyện với bạn cũng vui đấy",
    "Bạn có hay trò chuyện với khách không?",
    "Bạn có thể kể chuyện cho vui không?",
    "Bạn có biết kể chuyện cười không?",
    "Hôm nay tâm trạng bạn thế nào?",
    "Ngoài Hà Nội hôm nay có lạnh không?",
    "Bạn thích uống cà phê hay trà?",
    "Bạn làm việc buổi tối có buồn ngủ không?",
    "Cửa hàng mở cửa từ mấy giờ?",
    "Cửa hàng đóng cửa lúc mấy giờ?",
    "Bạn có thích công việc này không?",
    "Bạn làm việc ca sáng hay ca tối?",
    "Hôm nay có nhiều khách hỏi mua không?",
    "Bạn có hay gặp khách khó tính không?",
    "Bạn có thấy công việc này áp lực không?",
    "Bạn làm việc ở đây một mình hay nhiều người?",
    "Hôm nay có chương trình gì vui không?",
    "Bạn có hay nghe nhạc không?",
    "Bạn thích nghe nhạc thể loại gì?",
    "Bạn có hay xem phim không?",
    "Gần đây có bộ phim nào hay không?",
    "Bạn có hay chơi game không?",
    "Bạn có hay dùng mạng xã hội không?",
    "Bạn có hay đọc tin tức không?",
    "Hôm nay bạn ăn gì?",
    "Bạn có thích đồ ăn nhanh không?",
    "Bạn có hay đi du lịch không?",
    "Bạn thích đi biển hay đi núi?",
    "Bạn có thích thời tiết mát mẻ không?",
    "Bạn thấy hôm nay trời có đẹp không?",
    "Bạn có hay trò chuyện với khách quen không?",
    "Bạn có nhớ tên khách không?",
    "Bạn có thích nói chuyện với khách không?",
    "Hôm nay cửa hàng có khuyến mãi lớn không?",
    "Bạn có thấy hôm nay trôi qua nhanh không?",
    "Bạn có hay làm việc tăng ca không?",
    "Bạn có thấy công việc này thú vị không?",
    "Bạn có thích làm việc với khách hàng không?",
    "Bạn có hay gặp khách vui tính không?",
    "Bạn có hay gặp khách hỏi nhiều không?",
    "Bạn có hay gặp khách chỉ hỏi giá không?",
    "Bạn có hay gặp khách quay lại không?",
    "Bạn có thích giúp khách chọn sản phẩm không?",
    "Bạn có thấy vui khi khách hài lòng không?",
    "Bạn có hay cười khi nói chuyện không?",
    "Bạn có thấy hôm nay đông khách hơn hôm qua không?",
    "Bạn có thích không khí cửa hàng không?",
    "Bạn có hay làm việc cuối tuần không?",
    "Bạn có hay nghỉ lễ không?",
    "Bạn có mong đến giờ tan ca không?",
    "Bạn có thích làm việc buổi tối không?",
    "Bạn có hay nói chuyện với đồng nghiệp không?",
    "Bạn có thấy hôm nay thời gian trôi nhanh không?",
    "Bạn có thích trò chuyện không?",
    "Bạn có hay gặp khách quen không?",
    "Bạn có nhớ khách cũ không?",
    "Bạn có thấy hôm nay vui không?",
    "Bạn có hay cười không?",
    "Bạn có thích công việc hiện tại không?",
    "Bạn có thấy công việc này phù hợp không?",
    "Bạn có muốn đổi công việc không?",
    "Bạn có thấy hôm nay mệt không?",
    "Bạn có thấy hôm nay ổn không?",
    "Bạn có hay suy nghĩ nhiều không?",
    "Bạn có thấy hôm nay bình thường không?",
    "Bạn có thích nói chuyện phiếm không?",
    "Bạn có hay bắt chuyện với khách không?",
    "Bạn có thích không khí buổi tối không?",
    "Bạn có hay nói chuyện với người lạ không?",
    "Bạn có thấy hôm nay dễ chịu không?",
    "Bạn có hay cười khi nói chuyện với khách không?",
    "Bạn có thấy hôm nay là một ngày tốt không?",
    "Bạn có hay trò chuyện cho vui không?",
    "Bạn có thấy hôm nay trôi qua nhanh không?",
    "Bạn có thấy hôm nay nhẹ nhàng không?"
]